# Generated by Django 5.1.2 on 2025-02-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(blank=True, default='Not accepted', max_length=64),
        ),
        migrations.AlterField(
            model_name='details',
            name='status',
            field=models.CharField(blank=True, default='Waiting', max_length=64),
        ),
    ]
