# Generated by Django 5.1.2 on 2025-02-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0002_requests_status_alter_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fio',
            field=models.CharField(blank=True, default='No name', max_length=64),
        ),
    ]
