# Generated by Django 5.1.2 on 2025-02-27 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0003_customuser_fio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='price',
        ),
    ]
