# Generated by Django 5.1.2 on 2025-02-27 06:21

import ak_rest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0004_remove_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=ak_rest.models.user_directory_path),
        ),
    ]
