# Generated by Django 5.1.2 on 2025-02-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0005_product_category_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsitems',
            name='count',
        ),
    ]
