# Generated by Django 5.1.2 on 2025-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0006_remove_requestsitems_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='product_id',
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
