# Generated by Django 5.1.2 on 2025-02-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0007_remove_items_product_id_items_category_items_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
