# Generated by Django 5.1.2 on 2025-02-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0008_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsitems',
            name='status',
        ),
    ]
