# Generated by Django 5.1.2 on 2025-02-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0009_remove_requestsitems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
