# Generated by Django 5.1.2 on 2025-03-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0010_alter_requests_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requests',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requests',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requests',
            name='window_type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
