# Generated by Django 5.1.2 on 2025-03-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0011_requests_height_requests_price_requests_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='window_image',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
