# Generated by Django 5.1.2 on 2025-03-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_rest', '0012_requests_window_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsitems',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
